// Generates the Storybook "Foundations" pages from the tokens, so Storybook shows the real values
// and never a hand-copied table that drifts: `npm run foundations`.
//   Sources: src/tokens/index.css (:root) and tailwind.config.ts (+ Tailwind's default scale).
//   Output:  src/foundations/generated/*.mdx — do not edit by hand.
// The values are written into the MDX as text, because the Storybook MCP (docs-show) returns the
// MDX text to the agent: a table computed at runtime would reach it empty.
// src/foundations/foundations.test.ts fails when the pages are older than the tokens.
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
export const OUT_DIR = path.join(root, 'src/foundations/generated')

const HEADER = (title, source) =>
  `{/* Generated by scripts/foundations.mjs from ${source}. Do not edit — change the tokens and run \`npm run foundations\`. */}\n\n` +
  `import { Meta } from '@storybook/addon-docs/blocks';\n\n<Meta title="Foundations/${title}" />\n\n`

/** `--name: value; /* comment *\/` lines of the :root block, with the section comment above them. */
function parseRootTokens(css) {
  const start = css.indexOf(':root {')
  const end = css.indexOf('\n  }', start)
  const tokens = []
  let section = ''
  for (const line of css.slice(start, end).split('\n')) {
    const heading = line.match(/^\s*\/\*\s*(.+?)\s*\*\/\s*$/)
    if (heading) section = heading[1]
    const m = line.match(/^\s*--([\w-]+):\s*([^;]+);\s*(?:\/\*\s*(.*?)\s*\*\/)?/)
    if (m) tokens.push({ name: m[1], value: m[2].trim(), note: m[3] ?? '', section })
  }
  return tokens
}

const isHsl = (v) => /^\d+(\.\d+)?\s+\d+(\.\d+)?%\s+\d+(\.\d+)?%$/.test(v)

function hslToHex(value) {
  const [h, s, l] = value.split(/\s+/).map((x) => parseFloat(x))
  const a = (s / 100) * Math.min(l / 100, 1 - l / 100)
  const f = (n) => {
    const k = (n + h / 30) % 12
    const c = l / 100 - a * Math.max(-1, Math.min(k - 3, 9 - k, 1))
    return Math.round(c * 255).toString(16).padStart(2, '0')
  }
  return `#${f(0)}${f(8)}${f(4)}`
}

/** CSS variable → Tailwind colour name ('sidebar-accent', 'primary'), from tailwind.config colors. */
function colourClasses(colors, prefix = '') {
  const map = {}
  for (const [key, value] of Object.entries(colors)) {
    const name = key === 'DEFAULT' ? prefix : prefix ? `${prefix}-${key}` : key
    if (typeof value === 'string') {
      const v = value.match(/var\(--([\w-]+)\)/)
      if (v) (map[v[1]] ??= []).push(name)
    } else Object.assign(map, mergeLists(map, colourClasses(value, name)))
  }
  return map
}
function mergeLists(a, b) {
  const out = { ...a }
  for (const [k, v] of Object.entries(b)) out[k] = [...(out[k] ?? []), ...v]
  return out
}

const rem = (v) => (/^[\d.]+rem$/.test(v) ? `${parseFloat(v) * 16}px` : v)
const code = (s) => '`' + s + '`'
const row = (cells) => `| ${cells.join(' | ')} |`
const table = (head, rows) => [row(head), row(head.map(() => '---')), ...rows.map(row)].join('\n')

export async function buildFoundations() {
  const css = await readFile(path.join(root, 'src/tokens/index.css'), 'utf8')
  const { default: config } = await import(pathToFileURL(path.join(root, 'tailwind.config.ts')).href)
  const { default: defaults } = await import('tailwindcss/defaultTheme.js')
  const ext = config.theme.extend
  const tokens = parseRootTokens(css)
  const byName = Object.fromEntries(tokens.map((t) => [t.name, t]))
  const varValue = (expr) => {
    const v = expr.match(/var\(--([\w-]+)\)/)
    return v ? byName[v[1]]?.value ?? expr : expr
  }
  const pages = {}

  // Colours
  const classes = colourClasses(ext.colors)
  let mismatches = 0
  const colourRows = tokens
    .filter((t) => isHsl(t.value))
    .map((t) => {
      const rendered = hslToHex(t.value)
      const figma = t.note.match(/#[0-9a-f]{6}/i)?.[0]?.toLowerCase()
      const differs = figma && figma !== rendered
      if (differs) mismatches++
      return [
        code(t.name),
        classes[t.name] ? classes[t.name].map((c) => code(c)).join(', ') : '— (без класса)',
        rendered,
        figma ? (differs ? `${figma} ⚠️` : figma) : '—',
        code(t.value),
        t.section,
        t.note.replace(/#[0-9a-f]{6}/gi, '').replace(/\s+—?\s*$/, '').trim(),
      ]
    })
  pages['colors.mdx'] =
    HEADER('Colors', 'src/tokens/index.css + tailwind.config.ts').replace(
      "import { Meta } from '@storybook/addon-docs/blocks';",
      "import { Meta } from '@storybook/addon-docs/blocks';\nimport { TokenSwatches } from '../token-swatches';",
    ) +
    `# Colors\n\nКласс Tailwind = префикс + имя: \`bg-surface\`, \`text-muted-foreground\`, \`border-divider\`. ` +
    `Хардкод цвета запрещён (\`npm run lint:tokens\`). Значения — светлая тема; тёмная (\`.dark\`) в sandbox не используется.\n\n` +
    `**В браузере** — hex, который даёт HSL токена; **Figma** — hex из комментария к токену. ` +
    `⚠️ — не совпадают: HSL токена округлён (${mismatches} шт.). Новые токены задаются точным HSL.\n\n` +
    table(['Token', 'Tailwind', 'В браузере', 'Figma', 'HSL', 'Группа', 'Комментарий'], colourRows) +
    `\n\n## Образцы\n\n<TokenSwatches />\n`

  // Typography
  const families = Object.entries(ext.fontFamily).map(([k, v]) => [code(`font-${k}`), v.join(', ')])
  const customSizes = Object.entries(ext.fontSize).map(([k, v]) => {
    const [size, opts] = Array.isArray(v) ? v : [v, {}]
    return [
      code(`text-${k}`),
      rem(varValue(size)),
      rem(varValue(opts.lineHeight ?? '')),
      opts.letterSpacing ? varValue(opts.letterSpacing) : '—',
      'токен sandbox',
    ]
  })
  const baseSizes = ['xs', 'sm', 'base', 'lg', 'xl', '2xl', '3xl'].map((k) => {
    const [size, opts] = defaults.fontSize[k]
    return [code(`text-${k}`), rem(size), rem(opts.lineHeight), '—', 'Tailwind']
  })
  pages['typography.mdx'] =
    HEADER('Typography', 'tailwind.config.ts + Tailwind default theme') +
    `# Typography\n\nШрифт по умолчанию — Geist (\`body\`, \`src/index.css\`). Вес: \`font-normal\` 400, \`font-medium\` 500, \`font-semibold\` 600.\n\n` +
    `## Семейства\n\n${table(['Класс', 'Стек'], families)}\n\n` +
    `## Размеры\n\n${table(['Класс', 'Размер', 'Line height', 'Letter spacing', 'Откуда'], [...customSizes, ...baseSizes])}\n\n` +
    `Line height у размера можно переопределить: \`leading-5\` = 20px (так в Figma у \`text-base\` в Booking Header).\n`

  // Spacing
  const figmaNames = { 0.5: '2px', 1: 'p-1 / gap-1', 1.5: 'p-1,5', 2: 'p-2 / gap-2', 3: 'p-3', 4: 'p-4', 5: 'p-5', 6: 'p-6', 8: 'p-8' }
  const spacingRows = ['px', '0.5', '1', '1.5', '2', '2.5', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '16']
    .map((k) => [code(k), rem(defaults.spacing[k]), figmaNames[k] ? code(figmaNames[k]) : ''])
  pages['spacing.mdx'] =
    HEADER('Spacing', 'Tailwind default theme') +
    `# Spacing\n\nОтступы и размеры — шкала Tailwind (1 = 4px), та же, что переменные Figma \`padding/p-N\`, \`gap/gap-N\`. ` +
    `Пример: \`px-4 py-2\` = 16 / 8, \`gap-4\` = 16px, \`size-7\` = 28px.\n\n` +
    table(['Шаг', 'px', 'Переменная Figma'], spacingRows) +
    `\n\nРазмеры раскладки вне шкалы (ширина sidebar, колонки экрана) — Foundations / Layout.\n`

  // Radius + shadows
  const radiusRows = Object.entries(ext.borderRadius).map(([k, v]) => {
    const value = v.replace(/var\(--([\w-]+)\)/g, (_, n) => byName[n]?.value ?? n)
    const px = value.replace(/^calc\(([\d.]+)rem - (\d+)px\)$/, (_, r, d) => `${parseFloat(r) * 16 - d}px`)
    return [code(`rounded-${k}`), rem(px), byName[v.match(/--([\w-]+)/)?.[1]]?.note ?? '']
  })
  const shadowRows = [
    ...Object.entries(ext.boxShadow).map(([k, v]) => [code(`shadow-${k}`), code(varValue(v)), byName[v.match(/--([\w-]+)/)?.[1]]?.note ?? '']),
    ...Object.entries(ext.dropShadow).map(([k, v]) => [code(`drop-shadow-${k}`), code(varValue(v)), byName[v.match(/--([\w-]+)/)?.[1]]?.note ?? '']),
  ]
  pages['radius-and-shadows.mdx'] =
    HEADER('Radius and Shadows', 'src/tokens/index.css + tailwind.config.ts') +
    `# Radius and Shadows\n\n## Radius\n\n${table(['Класс', 'Значение', 'Где'], radiusRows)}\n\n` +
    `## Shadows\n\n\`shadow-*\` — box-shadow, \`drop-shadow-*\` — filter (повторяет форму, не обрезается).\n\n${table(['Класс', 'Значение', 'Где'], shadowRows)}\n`

  return pages
}

// CLI: write the pages.
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const pages = await buildFoundations()
  await mkdir(OUT_DIR, { recursive: true })
  for (const [file, content] of Object.entries(pages)) await writeFile(path.join(OUT_DIR, file), content)
  console.log(`Foundations: ${Object.keys(pages).join(', ')} → src/foundations/generated/`)
}
