// Regenerates the colour palette from Figma "shadcn kit - Trava" → Foundations → Primitives
// ("Tailwind Colors"): 22 scales × 11 steps, identical to Tailwind 3 default colours.
//   npm run tokens:palette
// Writes src/tokens/palette.ts (hex, for Storybook and tests) and src/tokens/palette.css
// (exact HSL variables, `--palette-<scale>-<step>`, for aliases in src/tokens/index.css).
import { writeFileSync } from 'node:fs'
import colors from 'tailwindcss/colors.js'

// Figma scale name → Tailwind key. Figma spells "Fuschia"; we use the correct "fuchsia".
const SCALES = [
  'slate', 'gray', 'zinc', 'neutral', 'stone', 'red', 'orange', 'amber', 'yellow', 'lime', 'green',
  'emerald', 'teal', 'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose',
]
const STEPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]

function hexToHsl(hex) {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
  const max = Math.max(r, g, b), min = Math.min(r, g, b), d = max - min
  const l = (max + min) / 2
  if (d === 0) return [0, 0, l * 100]
  const s = d / (1 - Math.abs(2 * l - 1))
  const h = max === r ? ((g - b) / d) % 6 : max === g ? (b - r) / d + 2 : (r - g) / d + 4
  return [(h * 60 + 360) % 360, s * 100, l * 100]
}
const num = (n) => String(+n.toFixed(3))

const palette = {}
let css = '/* Generated by scripts/generate-palette.mjs — do not edit by hand. Source: Figma Primitives. */\n@layer base {\n  :root {\n'
for (const scale of SCALES) {
  palette[scale] = {}
  for (const step of STEPS) {
    const hex = colors[scale][step].toLowerCase()
    palette[scale][step] = hex
    const [h, s, l] = hexToHsl(hex)
    css += `    --palette-${scale}-${step}: ${num(h)} ${num(s)}% ${num(l)}%; /* ${hex} */\n`
  }
}
css += '  }\n}\n'

const ts = `// Generated by scripts/generate-palette.mjs — do not edit by hand.
// Source: Figma "shadcn kit - Trava" → Foundations → Primitives → Tailwind Colors.
export const PALETTE_STEPS = ${JSON.stringify(STEPS)} as const
export type PaletteStep = (typeof PALETTE_STEPS)[number]

export const PALETTE = ${JSON.stringify(palette, null, 2)} as const satisfies Record<string, Record<PaletteStep, string>>

export type PaletteScale = keyof typeof PALETTE
`
writeFileSync(new URL('../src/tokens/palette.css', import.meta.url), css)
writeFileSync(new URL('../src/tokens/palette.ts', import.meta.url), ts)
console.log(`✓ ${SCALES.length} scales × ${STEPS.length} steps`)
