import type { Meta, StoryObj } from '@storybook/react-vite'
import { expect } from 'storybook/test'
import { PALETTE, PALETTE_STEPS } from './palette'
import {
  CHART_COLORS,
  SEMANTIC_GROUPS,
  UNBOUND_FIGMA_COLORS,
  type SemanticColor,
} from './semantic-colors'

// Colour foundations from Figma "shadcn kit - Trava" → Foundations. Swatches are painted with the
// CSS variables the app uses, so the page shows what is actually bound, not a copy of the values.
// Each story is also a test: the browser-computed colour of every bound swatch must equal Figma's.

const meta = {
  title: 'Foundations/Colors',
  tags: ['ai-generated'],
  parameters: { layout: 'padded' },
} satisfies Meta

export default meta
type Story = StoryObj<typeof meta>

const paletteVar = (scale: string, step: number) => `hsl(var(--palette-${scale}-${step}))`

function Swatch({ color, hex, expected }: { color: string; hex: string; expected?: boolean }) {
  return (
    <div
      aria-hidden
      data-swatch={hex}
      data-expected={expected === false ? 'differs' : 'match'}
      className="h-10 w-full rounded-md border border-border"
      style={{ backgroundColor: color }}
    />
  )
}

function PaletteScale({ scale }: { scale: keyof typeof PALETTE }) {
  return (
    <section aria-label={scale} className="mb-6">
      <h3 className="mb-2 text-sm font-medium capitalize">{scale}</h3>
      <div className="grid grid-cols-11 gap-2">
        {PALETTE_STEPS.map((step) => (
          <div key={step} className="min-w-0">
            <Swatch color={paletteVar(scale, step)} hex={PALETTE[scale][step]} />
            <p className="mt-1 font-mono text-xs text-muted-foreground">{step}</p>
            <p className="font-mono text-xs text-muted-foreground">{PALETTE[scale][step]}</p>
          </div>
        ))}
      </div>
    </section>
  )
}

function SemanticTable({ mode }: { mode: 'light' | 'dark' }) {
  return (
    <div className={mode === 'dark' ? 'dark bg-background p-4 text-foreground' : 'p-4'}>
      {SEMANTIC_GROUPS.map((group) => (
        <table key={group.title} className="mb-6 w-full text-left text-sm">
          <caption className="mb-2 text-left text-sm font-medium">{group.title}</caption>
          <thead className="text-xs text-muted-foreground">
            <tr>
              <th scope="col" className="w-16 py-1 font-normal"><span className="sr-only">Colour</span></th>
              <th scope="col" className="py-1 font-normal">Figma</th>
              <th scope="col" className="py-1 font-normal">CSS variable</th>
              <th scope="col" className="py-1 font-normal">Tailwind</th>
              <th scope="col" className="py-1 font-normal">Hex (Figma)</th>
              <th scope="col" className="py-1 font-normal">Status</th>
            </tr>
          </thead>
          <tbody>
            {group.colors.map((color) => (
              <SemanticRow key={color.var} color={color} mode={mode} />
            ))}
          </tbody>
        </table>
      ))}
    </div>
  )
}

function SemanticRow({ color, mode }: { color: SemanticColor; mode: 'light' | 'dark' }) {
  const differs = color.pending === true && mode === 'light'
  return (
    <tr className="border-t border-border">
      <td className="py-2 pr-3">
        <Swatch color={`hsl(var(--${color.var}))`} hex={color[mode]} expected={!differs} />
      </td>
      <td className="py-2">{color.figma}</td>
      <td className="py-2 font-mono text-xs">--{color.var}</td>
      <td className="py-2 font-mono text-xs">{color.tailwind}</td>
      <td className="py-2 font-mono text-xs">{color[mode]}</td>
      <td className="py-2 text-xs text-muted-foreground">
        {differs ? 'Differs from Figma — pending decision (#22)' : 'Matches Figma'}
      </td>
    </tr>
  )
}

function toRgb(hex: string): string {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16))
  return `rgb(${r}, ${g}, ${b})`
}

/** Every swatch flagged as matching must be painted exactly Figma's colour. */
async function expectSwatchesMatchFigma(root: HTMLElement) {
  const swatches = root.querySelectorAll<HTMLElement>('[data-swatch][data-expected="match"]')
  await expect(swatches.length).toBeGreaterThan(0)
  for (const swatch of swatches) {
    await expect(getComputedStyle(swatch).backgroundColor).toBe(toRgb(swatch.dataset.swatch!))
  }
}

export const Palette: Story = {
  name: 'Palette',
  parameters: {
    docs: {
      description: {
        story:
          'Figma → Foundations → Primitives → "Tailwind Colors": 22 scales × 11 steps (50–950). ' +
          'Variables `--palette-<scale>-<step>` are generated by `npm run tokens:palette`. ' +
          'Components do not use them directly — they go through the semantic tokens below.',
      },
    },
  },
  render: () => (
    <div>
      {(Object.keys(PALETTE) as (keyof typeof PALETTE)[]).map((scale) => (
        <PaletteScale key={scale} scale={scale} />
      ))}
    </div>
  ),
  play: ({ canvasElement }) => expectSwatchesMatchFigma(canvasElement),
}

export const SemanticLight: Story = {
  name: 'Semantic — Light',
  parameters: {
    docs: {
      description: {
        story:
          'Figma → Foundations → Color → Light, bound to our CSS variables (`src/tokens/index.css`). ' +
          'A token that aliases a palette step is exact by construction. Rows marked "Differs" keep ' +
          'their old value until product/design decide (docs/open-questions.md #22).',
      },
    },
  },
  render: () => <SemanticTable mode="light" />,
  play: ({ canvasElement }) => expectSwatchesMatchFigma(canvasElement),
}

export const SemanticDark: Story = {
  name: 'Semantic — Dark',
  parameters: {
    docs: {
      description: {
        story:
          'Figma → Foundations → Color → Dark. Dark mode is not used in the app yet; the values are ' +
          'here so it can be switched on without another Figma pass. `Destructive` is inverted ' +
          '(light fill, dark text) exactly as in Figma.',
      },
    },
  },
  render: () => <SemanticTable mode="dark" />,
  play: ({ canvasElement }) => expectSwatchesMatchFigma(canvasElement),
}

export const ChartsAndUnbound: Story = {
  name: 'Charts and unbound',
  parameters: {
    docs: {
      description: {
        story:
          'Chart 1–5 exist in code for both modes; Figma Chart 2 (light) is #2a9d90, ours is teal ' +
          '#0d9488 (pending, #22). The alpha tokens below exist only in the Figma shadcn kit: we have ' +
          'no variable for them because the app writes opacity as a modifier (`bg-primary/50`).',
      },
    },
  },
  render: () => (
    <div className="space-y-6">
      {(['light', 'dark'] as const).map((mode) => (
        <section key={mode} aria-label={`Chart ${mode}`}>
          <h3 className="mb-2 text-sm font-medium capitalize">Chart — {mode}</h3>
          <div className="grid grid-cols-5 gap-2">
            {CHART_COLORS[mode].map((hex, i) => (
              <div key={hex}>
                <div aria-hidden className="h-10 rounded-md border border-border" style={{ backgroundColor: hex }} />
                <p className="mt-1 font-mono text-xs text-muted-foreground">Chart {i + 1} {hex}</p>
              </div>
            ))}
          </div>
        </section>
      ))}
      <table className="w-full text-left text-sm">
        <caption className="mb-2 text-left text-sm font-medium">Figma tokens without a variable</caption>
        <thead className="text-xs text-muted-foreground">
          <tr>
            <th scope="col" className="py-1 font-normal">Figma</th>
            <th scope="col" className="py-1 font-normal">Light</th>
            <th scope="col" className="py-1 font-normal">Dark</th>
          </tr>
        </thead>
        <tbody>
          {UNBOUND_FIGMA_COLORS.map((t) => (
            <tr key={t.figma} className="border-t border-border">
              <td className="py-2">{t.figma}</td>
              <td className="py-2 font-mono text-xs">{t.light}</td>
              <td className="py-2 font-mono text-xs">{t.dark}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  ),
}
