import type { Meta, StoryObj } from '@storybook/react-vite'
import { expect } from 'storybook/test'
import { PALETTE, PALETTE_STEPS } from './palette'
import {
  CHART_COLORS,
  SEMANTIC_GROUPS,
  UNBOUND_FIGMA_COLORS,
  type SemanticColor,
} from './semantic-colors'

// Light theme only: dark theme is not used or tested in the sandbox (decision 2026-09-29).
// Colour foundations from Figma "shadcn kit - Trava" → Foundations. Swatches are painted with the
// CSS variables the app uses, so the page shows what is actually bound, not a copy of the values.
// Each story is also a test: the browser-computed colour of every bound swatch must equal Figma's.

const meta = {
  title: 'Foundations/Colors',
  tags: ['ai-generated'],
  parameters: { layout: 'padded' },
} satisfies Meta

export default meta
type Story = StoryObj<typeof meta>

const paletteVar = (scale: string, step: number) => `hsl(var(--palette-${scale}-${step}))`

function Swatch({ color, hex }: { color: string; hex: string }) {
  return (
    <div
      aria-hidden
      data-swatch={hex}
      className="h-10 w-full rounded-md border border-border"
      style={{ backgroundColor: color }}
    />
  )
}

function PaletteScale({ scale }: { scale: keyof typeof PALETTE }) {
  return (
    <section aria-label={scale} className="mb-6">
      <h3 className="mb-2 text-sm font-medium capitalize">{scale}</h3>
      <div className="grid grid-cols-11 gap-2">
        {PALETTE_STEPS.map((step) => (
          <div key={step} className="min-w-0">
            <Swatch color={paletteVar(scale, step)} hex={PALETTE[scale][step]} />
            <p className="mt-1 font-mono text-xs text-muted-foreground">{step}</p>
            <p className="font-mono text-xs text-muted-foreground">{PALETTE[scale][step]}</p>
          </div>
        ))}
      </div>
    </section>
  )
}

function SemanticTable() {
  return (
    <div className="p-4">
      {SEMANTIC_GROUPS.map((group) => (
        <table key={group.title} className="mb-6 w-full text-left text-sm">
          <caption className="mb-2 text-left text-sm font-medium">{group.title}</caption>
          <thead className="text-xs text-muted-foreground">
            <tr>
              <th scope="col" className="w-16 py-1 font-normal"><span className="sr-only">Colour</span></th>
              <th scope="col" className="py-1 font-normal">Figma</th>
              <th scope="col" className="py-1 font-normal">CSS variable</th>
              <th scope="col" className="py-1 font-normal">Tailwind</th>
              <th scope="col" className="py-1 font-normal">Hex (Figma)</th>
              <th scope="col" className="py-1 font-normal">Status</th>
            </tr>
          </thead>
          <tbody>
            {group.colors.map((color) => (
              <SemanticRow key={color.var} color={color} />
            ))}
          </tbody>
        </table>
      ))}
    </div>
  )
}

function SemanticRow({ color }: { color: SemanticColor }) {
  return (
    <tr className="border-t border-border">
      <td className="py-2 pr-3">
        <Swatch color={`hsl(var(--${color.var}))`} hex={color.kept?.hex ?? color.light} />
      </td>
      <td className="py-2">{color.figma}</td>
      <td className="py-2 font-mono text-xs">--{color.var}</td>
      <td className="py-2 font-mono text-xs">{color.tailwind}</td>
      <td className="py-2 font-mono text-xs">{color.light}</td>
      <td className="py-2 text-xs text-muted-foreground">
        {color.kept ? `${color.kept.reason} (#22)` : 'Matches Figma'}
      </td>
    </tr>
  )
}

function toRgb(hex: string): string {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16))
  return `rgb(${r}, ${g}, ${b})`
}

/** Every swatch must be painted exactly the colour it claims: Figma's, or the kept one. */
async function expectSwatchesMatch(root: HTMLElement) {
  const swatches = root.querySelectorAll<HTMLElement>('[data-swatch]')
  await expect(swatches.length).toBeGreaterThan(0)
  for (const swatch of swatches) {
    await expect(getComputedStyle(swatch).backgroundColor).toBe(toRgb(swatch.dataset.swatch!))
  }
}

export const Palette: Story = {
  name: 'Palette',
  parameters: {
    docs: {
      description: {
        story:
          'Figma → Foundations → Primitives → "Tailwind Colors": 22 scales × 11 steps (50–950). ' +
          'Variables `--palette-<scale>-<step>` are generated by `npm run tokens:palette`. ' +
          'Components do not use them directly — they go through the semantic tokens below.',
      },
    },
  },
  render: () => (
    <div>
      {(Object.keys(PALETTE) as (keyof typeof PALETTE)[]).map((scale) => (
        <PaletteScale key={scale} scale={scale} />
      ))}
    </div>
  ),
  play: ({ canvasElement }) => expectSwatchesMatch(canvasElement),
}

export const Semantic: Story = {
  name: 'Semantic',
  parameters: {
    docs: {
      description: {
        story:
          'Figma → Foundations → Color → Light, bound to our CSS variables (`src/tokens/index.css`). ' +
          'A token that aliases a palette step is exact by construction; the play function checks ' +
          'every swatch. Three tokens keep a value other than Figma on purpose, for contrast ' +
          '(--ring, --sidebar-ring, --destructive-foreground): the row says why (open question #22).',
      },
    },
  },
  render: () => <SemanticTable />,
  play: ({ canvasElement }) => expectSwatchesMatch(canvasElement),
}

export const ChartsAndUnbound: Story = {
  name: 'Charts and unbound',
  parameters: {
    docs: {
      description: {
        story:
          'Chart 1–5 as in Figma. The alpha tokens below exist only in the Figma shadcn kit: we have ' +
          'no variable for them because the app writes opacity as a modifier (`bg-primary/50`).',
      },
    },
  },
  render: () => (
    <div className="space-y-6">
      <section aria-label="Chart">
        <h3 className="mb-2 text-sm font-medium">Chart</h3>
        <div className="grid grid-cols-5 gap-2">
          {CHART_COLORS.light.map((hex, i) => (
            <div key={hex}>
              <div aria-hidden className="h-10 rounded-md border border-border" style={{ backgroundColor: hex }} />
              <p className="mt-1 font-mono text-xs text-muted-foreground">Chart {i + 1} {hex}</p>
            </div>
          ))}
        </div>
      </section>
      <table className="w-full text-left text-sm">
        <caption className="mb-2 text-left text-sm font-medium">Figma tokens without a variable</caption>
        <thead className="text-xs text-muted-foreground">
          <tr>
            <th scope="col" className="py-1 font-normal">Figma</th>
            <th scope="col" className="py-1 font-normal">Value</th>
          </tr>
        </thead>
        <tbody>
          {UNBOUND_FIGMA_COLORS.map((t) => (
            <tr key={t.figma} className="border-t border-border">
              <td className="py-2">{t.figma}</td>
              <td className="py-2 font-mono text-xs">{t.light}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  ),
}
